/**
 * Read package.json version, write it as a literal constant into src/version.ts.
 * Wired into prebuild + prepublishOnly so dist always reflects package.json.
 * CI runs this then `git diff --exit-code src/version.ts` to catch drift.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as {
  version: string;
};

const out = `// AUTO-GENERATED by scripts/sync-version.ts. Do not edit by hand.
// Run \`pnpm sync:version\` after bumping package.json. CI enforces drift via
// \`git diff --exit-code src/version.ts\`.
export const VERSION = ${JSON.stringify(pkg.version)};
`;

writeFileSync(join(root, 'src', 'version.ts'), out);
console.log(`✓ src/version.ts → ${pkg.version}`);
