// AUTO-GENERATED by scripts/sync-version.ts. Do not edit by hand.
// Run `pnpm sync:version` after bumping package.json. CI enforces drift via
// `git diff --exit-code src/version.ts`.
export const VERSION = "1.0.0-alpha.0";
